### PR TITLE
Add Antarctic land masks

### PR DESCRIPTION
**Pull request by xylar**
Adds land masks extracted from the Bedmap2 data set that are either based on the ice mask or the grounded ice mask. The masks should include all land south of 60S latitude.

Also adds a driver script for combining either of these regions with the Natural Earth land coverage north of 60S.

### CODE REVIEW

**Comment by xylar** [comment]
Here is the script I used to extract the Bedmap2 data that had been interpolated to the 1/60 degree ETOPO1 grid:
https://gist.github.com/xylar/d8095949cd05d74e613c

**Comment by xylar** [comment]
@douglasjacobsen, take a look at these suggested additions.  If you prefer, you can cherry-pick in these commits to keep the commit tree from getting too tangled.

**Comment by douglasjacobsen** [comment]
@xylar Thanks, I just pulled these into my branch.

**Comment by xylar** [comment]
Okay, merged.  You'll need to delete the remote because I don't have permission.

**Pull request merged**
